#!/usr/bin/env bash
# changelog.sh - Generate a structured CHANGELOG.md from git history
# Usage: bash changelog.sh [output_file]
#
# Automatically categorizes commits into Added/Fixed/Changed/Removed
# based on conventional commit prefixes and common patterns.

set -euo pipefail

OUTPUT="${1:-CHANGELOG.md}"
PROJECT_NAME=$(basename "$(git rev-parse --show-toplevel 2>/dev/null || echo 'Project')")
DATE=$(date +%Y-%m-%d)

# Get the last tag, or use the initial commit if no tags exist
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
if [ -z "$LAST_TAG" ]; then
  RANGE="HEAD"
  VERSION="Unreleased"
else
  RANGE="${LAST_TAG}..HEAD"
  # Try to determine next version from tag pattern
  VERSION="Unreleased (since ${LAST_TAG})"
fi

# Collect commits
COMMITS=$(git log ${RANGE} --pretty=format:"%s|%h|%an" --no-merges 2>/dev/null || echo "")

if [ -z "$COMMITS" ]; then
  echo "No new commits found since ${LAST_TAG:-initial commit}."
  exit 0
fi

# Category arrays
ADDED=""
FIXED=""
CHANGED=""
REMOVED=""
OTHER=""

# Categorize each commit
while IFS='|' read -r subject hash author; do
  # Normalize subject to lowercase for matching
  lower_subject=$(echo "$subject" | tr '[:upper:]' '[:lower:]')
  entry="- ${subject} (\`${hash}\`) — ${author}"

  case "$lower_subject" in
    feat:*|feat\(*|add:*|add\ *|added\ *|"new "*|"create "*|"implement "*|"introduce "*)
      ADDED="${ADDED}\n${entry}"
      ;;
    fix:*|fix\(*|bugfix:*|hotfix:*|"fix "*|"fixed "*|"resolve "*|"patch "*)
      FIXED="${FIXED}\n${entry}"
      ;;
    "remove "*|"removed "*|"delete "*|"deleted "*|"drop "*|"deprecate "*)
      REMOVED="${REMOVED}\n${entry}"
      ;;
    refactor:*|refactor\(*|"update "*|"updated "*|"change "*|"changed "*|"modify "*|"improve "*|"upgrade "*|"migrate "*|"rename "*|"move "*|chore:*|docs:*|style:*|perf:*|ci:*|build:*|test:*)
      CHANGED="${CHANGED}\n${entry}"
      ;;
    *)
      # Try keyword-based fallback
      if echo "$lower_subject" | grep -qE '(add|create|new|implement|introduce|feature)'; then
        ADDED="${ADDED}\n${entry}"
      elif echo "$lower_subject" | grep -qE '(fix|bug|resolve|patch|repair)'; then
        FIXED="${FIXED}\n${entry}"
      elif echo "$lower_subject" | grep -qE '(remove|delete|drop|deprecat)'; then
        REMOVED="${REMOVED}\n${entry}"
      elif echo "$lower_subject" | grep -qE '(update|change|modify|improve|refactor|upgrade|migrate|rename|move)'; then
        CHANGED="${CHANGED}\n${entry}"
      else
        CHANGED="${CHANGED}\n${entry}"
      fi
      ;;
  esac
done <<< "$COMMITS"

# Build the CHANGELOG
{
  echo "# Changelog"
  echo ""
  echo "All notable changes to **${PROJECT_NAME}** are documented in this file."
  echo ""
  echo "## [${VERSION}] — ${DATE}"
  echo ""

  if [ -n "$ADDED" ]; then
    echo "### Added"
    echo -e "$ADDED"
    echo ""
  fi

  if [ -n "$FIXED" ]; then
    echo "### Fixed"
    echo -e "$FIXED"
    echo ""
  fi

  if [ -n "$CHANGED" ]; then
    echo "### Changed"
    echo -e "$CHANGED"
    echo ""
  fi

  if [ -n "$REMOVED" ]; then
    echo "### Removed"
    echo -e "$REMOVED"
    echo ""
  fi

  echo "---"
  echo "_Generated by [changelog.sh](./changelog.sh) on ${DATE}_"
} > "$OUTPUT"

echo "✅ CHANGELOG written to ${OUTPUT}"
echo "   $(echo -e "$COMMITS" | wc -l) commits categorized."
